# Generated by Django 5.1.1 on 2024-10-14

import django.utils.timezone
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=300,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(max_length=200, null=True, blank=True),
                ),
                (
                    "unsubscribe_token",
                    models.CharField(
                        default=uuid.uuid4, max_length=100, unique=True
                    ),
                ),
                (
                    "subscription_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("last_sent", models.DateTimeField(null=True, blank=True)),
            ],
        ),
    ]
