apiVersion: v1
kind: Secret
metadata:
    name: django-server-secret
    labels:
        app: gnome-nepal-server
type: Opaque
data:
    #ENC[AES256_GCM,data:+FBTUXN5s4jT6bifQCnLA9KyELdP,iv:++fj8sSRB3duO75WwShTIOIKVGozZMirlbDtqS6fPxE=,tag:yIa9fLKSCo4rtWSt92mMTw==,type:comment]
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:oQC++v/FPwpeMXNgMWRuQzBOiEw2OnSolqqanVLLNAfpfMhttb/+qxXBE18=,iv:qDsTBcOmhMI0I/YqukPw8mSasLKFIMg+TaMAddnjPLQ=,tag:zYO03rG+8ab5QkNYyz08Nw==,type:str]
    #ENC[AES256_GCM,data:POBp7ewMPv/MBC0d0Ht+ZKr87Iqt,iv:7rrX/E97+C0Isoa9lp1OwFSgKp1oGRcegjIEnn1ahTY=,tag:kmQTNDo5KmB+2ZSEWhygig==,type:comment]
    CACHE_HOST: ENC[AES256_GCM,data:t2K3WZYkzdNXYFEhiOYuRIwJlx1suTrGcT98aNt9tOA=,iv:mns/7J4Pf2mytMGXpjeCmnpqCSUB488feeunQNUvx0M=,tag:X2MxbQhJbSTDbKPX2RdAcg==,type:str]
    #ENC[AES256_GCM,data:2ORBHuHOK3udQoHKziN7FNtQX20Q,iv:R8yEUa7quhoi+6RxYDv13mtLDyQdQDNJhUcnemBm05o=,tag:Mqk5Lx7Lv5urtZnfSstg0w==,type:comment]
    CELERY_BROKER_URL: ENC[AES256_GCM,data:SgaeKyHVTpuLAPKnXDNNRBN6sF+ihusflXw8qA==,iv:KTZFspWZlJlYAhgCPIWN79Iwwfwe8rgmYNG6ZpGiBT4=,tag:NfQYl3IgtN3KdzrIJCGu8Q==,type:str]
    #ENC[AES256_GCM,data:Nug7oB/J+4rNgybUBzzoXec+4twZ,iv:ZwXzL+JMzbh+3SUVFCRd3xVm/8y3DtZPon6tOGiRfvI=,tag:06PSeAcZt38eMUuGNn++Xw==,type:comment]
    DB_NAME: ENC[AES256_GCM,data:8MlcgnuI3PHC92Zo,iv:LMzr0njJw40InI+lKChxn0lMbLXbvuPZmqZuLHuZk/k=,tag:ZzYJjDbv86O5m5xHBKblqA==,type:str]
    #ENC[AES256_GCM,data:Dt3gEGgj2NeVx0p1TTX0GEPgAhyB,iv:S4s8SWaCXGIlj1LO2ymbkfu73p/JtCBOW4ihyStdGSc=,tag:grBhQuQHkMehaXyVDXVMLQ==,type:comment]
    DB_USER: ENC[AES256_GCM,data:GzdHchoxsJ0=,iv:FcnVs/mnAmC2Zsxw8iiq9AJzI9IAviUOJ/klNM+vjZE=,tag:54QPmDzBibmclwyRkB+keg==,type:str]
    #ENC[AES256_GCM,data:6eaIrYWyjL2+D6ZbChsVRPAd1/9n,iv:SilaL4ALHYMV3qwtaju05KfLnq+8YZr2y2gwf39+m/Y=,tag:etRsH9YLtU6jNrD8onb31w==,type:comment]
    DB_PASSWORD: ENC[AES256_GCM,data:S2CRSVUOYTFKEHQG,iv:w/8QkVNdaHOkQVMzBLNaLc+oXzhJRE8CR6sEJM+1Tck=,tag:/+23uxDq045TZfuMdSNW1A==,type:str]
    #ENC[AES256_GCM,data:qswuKffc1CUjHM6cuO9rjsPeoeVE71w=,iv:o9RR0tkIMbBFWWw3BKQ+bT3U3bTurGmOXe2lu4DtNKU=,tag:znpq7MpMYnY7SoN+eOCI/Q==,type:comment]
    DB_HOST: ENC[AES256_GCM,data:1fW9+FS4da7WFWP5C+gPDjSLkY1yUZlxxICdXbpFtOl/yaLfa73MYziHizy5CppK6X+368LEiW/MFJPC,iv:5Nqj+Zz8Sk1vnl3JQkw7EaVMg1rorfEMlg/D6Uq+Q0g=,tag:rR3PyS5D9ZcV+ClJ+Owk/A==,type:str]
    #ENC[AES256_GCM,data:vKE/pGvJNyfq9K+e4xoiyKub9Kvt,iv:RzW71d3BtfoTLwpUF20zdtWp+MkfcZMQx9sDQ5O5iI4=,tag:Dd66dQjQ0wzQSL/gGzmllA==,type:comment]
    DB_PORT: ENC[AES256_GCM,data:3Oorqu6JXZI=,iv:1weJX+cI2vJY0VaR5cJWWTVrOjjWfu8w2/mlnwkhIxU=,tag:dfph3Mc88yws6c4AGM85cg==,type:str]
    #ENC[AES256_GCM,data:8qlEkDqJV8oTKsAEM/PCVhJJFlBUA7xSeIt7OOiQN3Zf,iv:CPfSSujT5JmsvANPPFXPofpmCmpHxVRVcNjXwZI0KJc=,tag:hkT5UvhFUTv2IMluW0mNQw==,type:comment]
    SENTRY_DSN: ""
    #ENC[AES256_GCM,data:nY6IMYTU6rbln41BPKODDUn1Ztaem9aSiKFMb/6runw9XHQ5qQ==,iv:c1u2Y3bfzMAQpMWbmWTQFrwn9maVzK1vEBCTGjwVAuM=,tag:rgEiKOcVlQ1jebylHoelOg==,type:comment]
    DJANGO_DEBUG: ENC[AES256_GCM,data:mdNPJnoJrZY=,iv:LYr7JfYkg5SBspSHConYrVeXB+zv+JDDjNHLjxkKrh0=,tag:xSLuT7fuFRsAPlM1kse/iw==,type:str]
    #ENC[AES256_GCM,data:yb2bc+gVVCMkMG9Y1bdpLQkhiwlR,iv:HIxORBVRZye6WXni0kpUS/2Lh8BVyrLQ6pZRYc46PDE=,tag:WQ+fS3JoIM+zSUJYr9uSuQ==,type:comment]
    DJANGO_ALLOWED_HOSTS: ENC[AES256_GCM,data:X+PSR4UkzLtmQvX9s31abP4evRNINxZ6gO4BOotIk7Jx0cu/ytK0/U6stBzkGAgzJ+BWa6y+rx889Xnysf0UDyTA/lISLt0FZJDxtRN1Xb6kzBOOPprl4g==,iv:xmNPzyItDmy/m6MBnJLagIkc/Cln2Z8g3cHVz9JVteQ=,tag:edfrPN8fSHNqY7Mc40HEPQ==,type:str]
    #ENC[AES256_GCM,data:6k2pJzxvZCBb2C1Rk256KsCDubwL,iv:g7svq5iLCyvZQob+gMMXSimVPZ7B6EELMNnQ3YIhxqo=,tag:glXCOpallO9tn9WktQDzkQ==,type:comment]
    DJANGO_ADMIN_USERNAME: ENC[AES256_GCM,data:zLNz+dFH7waPbCriOw2EpA==,iv:JtpKzmv/xZ/P5vZDMk6DJHbZ7lavWwx8VlDJFS2G9KQ=,tag:eAmUJxNfm4wJYboNiePZ5w==,type:str]
    #ENC[AES256_GCM,data:Xp4WUuIV1zQlPMoqSuC4NwNcMX1O,iv:iEv6beNnMI/j0udRGclvVx+R0LO9l0DlWNuX6IlQaxY=,tag:9pUPlMrMViKi1Xv80eQKeQ==,type:comment]
    DJANGO_ADMIN_PASSWORD: ENC[AES256_GCM,data:yMNE6qKrrXp6YWqW7jQVXA==,iv:bSDjGoe5wgdll3NI+H9ySCVW3xa5ZLnMDEvWhdFfZoo=,tag:zrLCPIRwGz2TLwDxuh3v4A==,type:str]
    #ENC[AES256_GCM,data:W97QFoV8PmRyUByFaRIzUmvDYOhV,iv:HzgARYLzjRi8bcReDKMxgRRLHypmSQGXJrIUjBHPvjU=,tag:zL5ui6yQrdWcAL0kNni2GQ==,type:comment]
    DJANGO_ADMIN_EMAIL: ENC[AES256_GCM,data:unYGe7hQjWKf2EkLCMFVY0HBxtqH1ouR,iv:kR2grRIFB2qHNcXNdMJm5XUhsizvjyM05X56m44IoiE=,tag:TeIMqIeEdAepB91a53BCnQ==,type:str]
    #ENC[AES256_GCM,data:b8tOl8pzEh62DpSNlZJ4XCjs8i6MpiA6N6qbbSKQDwZI53gaz0IWefg=,iv:BoGnpb6BATD/9isjFV+ciFjFNWcOlKhIB80r/1e9LRI=,tag:1GgALqnjN7G6POiRJT80Tw==,type:comment]
    DOCKERFILE_TARGET: ENC[AES256_GCM,data:QPqMdMV9N+Mm0Z7vN2M+Qg==,iv:wEsJKSKud7b9PrKmzTFtBet1NAuOIRwTNlsFUsbwCqI=,tag:reOVTlQ+FBwpKH5RaY3/xA==,type:str]
    DJANGO_CSRF_TRUSTED_ORIGINS: ENC[AES256_GCM,data:pQk9saXsgAPLrmju/HdNvnL/araW+frxg9SccwbQ3UBuke8OxRZjOgxF3gx3bLsQ/Pg1dxMe33VPMJq5CO0mXaUefW0gjm3ftV5okWEr15OLR75F+jJEABAn8reypLoJJn9R5k9axk1/6OvNufPvBM0qkoNaf6XEk/7bE5dKgFarQ1yYU5oggWlEdIf4R9VQ1a6ZKg==,iv:EQeeMrZ7Q6B5UBVX+QSHREyq1G6TG7Zd68rQzrEJGdI=,tag:wXnqRH9t170Fd0UMkIwOiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v6dxu9u5tv5kqapzrws55vpudj4jvxuwu9ty3fve5cvwqv0z4vrq3yeezp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcUxvaVpnUjc2cWpGV2Z4
            U3BDa0NLMm1VMitER3ZFRzE0RFRnb2ZHekU0CnF6OExBUXRJd2V2cVdCQVFNRnU3
            RXI3WHhMQkg4TGtSNk9mem5LeFhkTGMKLS0tIEwyWGtsNlFiT0JWR2xuLy90S09t
            UlY3b0tqckM2UVZndE0rSkFiRm9SNWMKF0+kfuhcHD3shm/JsF7TnHvQmHf+Ofag
            WQMlYo9vE13iGIxoabB+dIJgVvuL0Qmyi8n3vgSHZJ8AIifBRt6k3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T19:39:36Z"
    mac: ENC[AES256_GCM,data:8YWm7yP6H6QeikZZGq5I3y8FLwrIDsVs8Nz8g8ZvNESGUKY9z2lxs0FiyBGDCizmXh/zyK+ekEi2LsCepOqvclAMhJ/FYDNTDoDyHr99I8Jf2bLwtjFYZYTC5Df7AR4WgNngBJ/J6EQMXyuJYZcDhFrmH4IpSP0b9WagT5MnuOg=,iv:vHawToaQ+hQ+GDycSOmVCnJ05EpT75l7YcrjLIbgyeE=,tag:Uq15r4435RuZMrHnYX5vdQ==,type:str]
    pgp: []
    encrypted_regex: ^(secret|key|data)$
    version: 3.9.1
