apiVersion: v1
kind: Secret
metadata:
    name: django-server-secret
    labels:
        app: gnome-nepal-server
type: Opaque
data:
    #ENC[AES256_GCM,data:AbF1QgvjsDcmm232ARjEBPDdx9OQ,iv:LheJ5ny9WUrQrthRKnBX1VopNhmEXF/OdEDhMmHbF2o=,tag:F0U7b4ubSTawg38VqQeoMw==,type:comment]
    MEDIA_ROOT: ENC[AES256_GCM,data:nXs+HEYYGOs=,iv:gXJL+gzM+IqPJDruqeJNNnjruBLak1GsOWYapX3f5e0=,tag:pmUy5JP22pMvEPd5Rcbe5w==,type:str]
    #ENC[AES256_GCM,data:cvETX4XOoQ7N0/X2X9DOwpna2cvp,iv:sSLRhH0rRXhOV2Vcm16U2mDQ0I6BmMwxDgD5SBbn1rA=,tag:/2IxQ9ooknm9pWk/NmAj/Q==,type:comment]
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:6SFqNmJS3aNwpPpaiaeURtLef9IKPCCkhlz47I0XHEc19OZj9yYF2lRNjeM=,iv:i0vgZ+JwKQ+/9wBvfZ9/d1vAHhCqfnOfMT/s9EnvoZo=,tag:248vCxwh5RcOq10nueMOZw==,type:str]
    #ENC[AES256_GCM,data:4BBgRNSKaPpHRjSuis/LiFphZMOK,iv:ncW9ROs3MwA5YYrn1mjNG2YTkM4gk/+s6nvwvaJvAQY=,tag:44bk/bAR+n2R39qoCr306g==,type:comment]
    CACHE_HOST: ENC[AES256_GCM,data:nYhz7x7nz9r/k+yChc/ESxqV75ru+XTIXLykP92XtZw=,iv:x1CYEUnwgQyyHNZahC3OOcQ7qVwytyiIHKTxHLuwWtU=,tag:tcHJ1bXplT8zTV5arRNpYA==,type:str]
    #ENC[AES256_GCM,data:V4y07tpCDqwpw/h8ibPE+NoSlZwr,iv:jh4Q4eY8DBAk37Sz+TD1JyzbexE9f11Bie4Hun3IQIY=,tag:zNKLrP8Wyk6uPSptTpcakA==,type:comment]
    CELERY_BROKER_URL: ENC[AES256_GCM,data:eyCr1TLQuwBEFInKV9wOpHTTyTNI7Z2WOBY57A==,iv:6bpyR7zI21WaIapnKrLqXqfNGt+f/8Vq7hPpmzQwYaQ=,tag:xM7C8f2pJfv68K1o34079A==,type:str]
    #ENC[AES256_GCM,data:T6OhZgWEFuoMvjsGet5H7MiDj3dl,iv:JfMm6ZiPIhNjxpEKa8CgMQeBRGdPeWr/MZ0s5qo7bYU=,tag:JG6NKIiD3MjGXhZ+nnrgYA==,type:comment]
    DB_NAME: ENC[AES256_GCM,data:lFbJrhiHAhSooBD0,iv:MKzoX9ZQHecVLSkUB8yqIEbbByV0lBfTXE1CZZ+A1Yo=,tag:iMY2/as9G+lH6qZiv8QmvA==,type:str]
    #ENC[AES256_GCM,data:Zp633i5F/2C+rSbKpflgtb+N//TV,iv:/ROaSM6x9eZo/kUen52bL+zkScVplGMeeKzGGZJ6z4M=,tag:oalxfoUyT21VKwEk5shg6w==,type:comment]
    DB_USER: ENC[AES256_GCM,data:eOsbDoQE2Ts=,iv:ovLFkW6IALJmEJXnQMSr4rubZOWq6wo9h7yp9sHsg9g=,tag:KsA6e5JgHE+jIkASMh9d+A==,type:str]
    #ENC[AES256_GCM,data:dInd+R4Z5C+mnmCnZcpyYAHuiWgF,iv:5ti7iHGfSFpDIcDv8P4TSm6c07ty2Inl6C5l40BD4vc=,tag:PwTn37Oz2UlF7tYe4cCcDQ==,type:comment]
    DB_PASSWORD: ENC[AES256_GCM,data:b5oqBuA69TBNodYL,iv:44sdlrjcWd6zIwWxaiEGAZU74S2En0Hjjv0xZCLax/M=,tag:G4dRoGgfozNBzE7IDkQJbQ==,type:str]
    #ENC[AES256_GCM,data:3H3NQwrNA/k7DmymyMrktyWkimdlh+Q=,iv:sxKWzdjS5FgNZIZy2uFez5iZA3lVO0U/lH/uJWH61cg=,tag:ZCZcJti1s+Du0ULJ0B38zQ==,type:comment]
    DB_HOST: ENC[AES256_GCM,data:wvhIonfiattP1kVza3zf/85YjJeolco+AtQnDBHYv1detb9Iz/ym3wU8PnmYnkv0jiAdDfpCEDO6vIZN,iv:/QndgL6iXrTQZgvnBQ7L14gwO9jiLy6uIuHcdpEgtu4=,tag:iVKPnTnR1AyNYZe/78+fyQ==,type:str]
    #ENC[AES256_GCM,data:dpzDlGX/Zj68YKZlhXHSVWdkRrkI,iv:EC07Hw/dyu12hpRrBAHOt0jTOm2nkzthQD5S/3zaUto=,tag:yr5dM+dm32Vfymbwgf7N1g==,type:comment]
    DB_PORT: ENC[AES256_GCM,data:jYRS/F+2o8U=,iv:eCh6YjeP5YGjPApP+Cj5PVbrVCTb1Y7AvzYxNlW8URg=,tag:s8s4PzygxKH4PRlVUmkB7w==,type:str]
    #ENC[AES256_GCM,data:Qws3/NtE+53UGvrl7T9dxGXOwQhvTW+KIV4G6icjCRza,iv:/1poczHaUgSucwtVcquMPQ8Kd3myzWYRwFmUPzg02+E=,tag:ISRwOPLPrGFNF+sH4QnLkw==,type:comment]
    SENTRY_DSN: ""
    #ENC[AES256_GCM,data:Pb0DfVAJmQCcRz5DV2nOOt+m+P9u8WqMzj3OoziUSHVRA9/jDw==,iv:uvTOnWzqoOCjr9PafFPeHSnfdcoi2yCkuBzGVGozvds=,tag:PYxND7VYboXagRAJiPtVGQ==,type:comment]
    DJANGO_DEBUG: ENC[AES256_GCM,data:g4A+cdU3mis=,iv:ldToWjykNTKJ9MywsbJiYOeLTGn0cac57qoWR+L6B94=,tag:F4ki9H4VWO2nG+p5qD/b0w==,type:str]
    #ENC[AES256_GCM,data:0wHJqvfE4pNPAfmsaWgetaaOCZBT,iv:9TfNFa18Ddj8oaoFQa6hbykjhYPgBWdHPmyTkcOUpB8=,tag:lMQWG/44izNjSIlpdnmChQ==,type:comment]
    DJANGO_ALLOWED_HOSTS: ENC[AES256_GCM,data:5Clu5axaKiFCN749Be7Z3bF4oP+n27bSBp8kE+eLiaWnv2OWmEtJLfB+CSGzezdixVm/t6ZL8ro8yeXWsmEDM03RK5IXUnKZK7vK7ThAqeGPi6ynBVgFlg==,iv:OchCIuYlgpg7zzP/2Lg0apjttJnZ++cL8OL3fKF12PA=,tag:y9hT7HzusrD3LR2KrusFqA==,type:str]
    #ENC[AES256_GCM,data:EUQrLIPZRaiaTyxZoNadolR7AaQ5,iv:IXVQ6ttSzkOLrCgvQZVVitEjQoDYeDZGPBehBFL/+5M=,tag:o+rxcbFGst+sZxXfwKN99Q==,type:comment]
    DJANGO_ADMIN_USERNAME: ENC[AES256_GCM,data:HxbF5Ntd93j9VARg+8PjZBBwDPM=,iv:EJS+HbA5s5L7mr8uatYzrUas5mWdBjCL+teuArvdiWI=,tag:+Nx8pdIvLVRAVtyEKERElA==,type:str]
    #ENC[AES256_GCM,data:3BmgZ/cV3c1Go0RdJgevltmMeYNK,iv:NVlzKI4DPUFX80ayWgPSeWpJXIDgLUz599QIuO17b5E=,tag:DfBv7/JwZZCkXvJJaiND9g==,type:comment]
    DJANGO_ADMIN_PASSWORD: ENC[AES256_GCM,data:NtForaKqH9z4AnZgMbFrqhEEGXdOwjHYJbu2TOvpPEGOOIzo,iv:DrqvrEuo8F8myBPUa9K2oShB1W89qmaJBMccAyoq2wI=,tag:kwwMhZ6ZfkbwTgeiYGmB1w==,type:str]
    #ENC[AES256_GCM,data:OWIs3nHCFbWAPzyIu2y8t87W39DW,iv:t5w5xJ5EiOye9XOZT8YrM8XekKWXeNc9eAMBAgxsAfY=,tag:2xW9GWXLPowpRLQuilWBeg==,type:comment]
    DJANGO_ADMIN_EMAIL: ENC[AES256_GCM,data:ftViOWfbxxv4jCqzpfIPPPQZ00EXLEUa,iv:ntARX/n0+vqfJmEISfElc6ppVeb7y8WgCUkK2NwUATE=,tag:Y2miKOvT9LOQMIEIBdjI3Q==,type:str]
    #ENC[AES256_GCM,data:t9dWfx2OHEEb1zfdAjk+AXzpAvbHe9miLenX9NhIARGz2T0XkHhpIGw=,iv:d/Zg625Ge8r57f5axevK3X6pFUwi3pe5uI2BKxAaA9I=,tag:LPFSCOwh/mqTPIbpCnTZwA==,type:comment]
    DOCKERFILE_TARGET: ENC[AES256_GCM,data:fdDVeFpPhpSnfBaZZUALDA==,iv:CxDVLhTOck8f7qc7coSMx4rOWXSJWl1uoo41vT6uQw8=,tag:MzNrL/VOyn2CCj5iuPGUdA==,type:str]
    DJANGO_CSRF_TRUSTED_ORIGINS: ENC[AES256_GCM,data:UJK5p6GbGK/WJ0C8SnNnGkBBPbs0zxfpW9O1m9qX+LkOjKnru2Ho0cZMFwq3xcUOl8/phc7HBWk7ROpRXlLA84xJHAei4S3YtSGGoQPMC9hObeRc/t+6nkBMZ1kNbGJ8HAMvL/U3tBHfhda0MAhHya5+wYviboPI8KZl4Zjsto40ypQIduVth0+zQbqVYj7Yg4AVEw==,iv:YGSyOYhc8waVAWB8415iDhI2X0t9k/nZ4rOTAYy/epQ=,tag:JTmY81GSBBJDdrlLVAAHKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v6dxu9u5tv5kqapzrws55vpudj4jvxuwu9ty3fve5cvwqv0z4vrq3yeezp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpblZIZDUydDlUb2dvb3hy
            bURncEw1R3VOMEpvYjNRS3RzbW03WXF4dEN3CjBaclpROHljMG1NWlcxN05hemNE
            cFd2VzM1YmcxQmtwcDJNOG1rQmRhRmMKLS0tICtzbnd5RGJUM1NWdnNBdmNtaWpF
            aVNIdVJnYTVRaXBjVVFQRm0yR0VNTUUKl8jVVsiFH7Q+bHPnP+SimT3TC++9Tk7g
            2SkBpO74dCi8sBmx2kUNfqKtEd8RmFJAfYJ3AgHTdNXJEbeNC8wYpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-15T17:12:45Z"
    mac: ENC[AES256_GCM,data:FJNfLdv+XgekGCIz9IHpxOamHDKERcQmWTNHALBSfkDmkF3Aoo5GMDFQXfb6epmv9rgANVlR8b4rRAGSxH6pPnVfStNaQDc37uVFmTwj0J7JG6fNTBjoXUDu1tFE/AghcuWy1nxPaVMNrqBej1aVd6vm4mCCxfHGbvlXfKOM3Nc=,iv:MlLMc/bxq1EpkFHut36vTQ1AiR9WQPeXoxvkPm+xRrE=,tag:lOI76681cWjJY1HJktBGvw==,type:str]
    pgp: []
    encrypted_regex: ^(secret|key|data)$
    version: 3.9.1
