# Generated by Django 5.1.1 on 2025-01-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0007_participant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="phone_number",
            field=models.CharField(max_length=14),
        ),
    ]
