# Generated by Django 5.1.1 on 2025-01-11 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_alter_participant_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="age",
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="participant",
            name="phone_number",
            field=models.CharField(
                max_length=14,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '9999999999'. Up to 14 digits allowed including +977",
                        regex="^\\+?[0-9]*$",
                    )
                ],
            ),
        ),
    ]
