# Generated by Django 5.1.1 on 2025-01-12 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0009_participant_age_alter_participant_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="requires_registration",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="participant",
            name="academy",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="participant",
            name="phone_number",
            field=models.CharField(
                max_length=14,
                validators=[
                    django.core.validators.RegexValidator(
                        message=(
                            "Phone number must be 10 digit",
                            "long and  Up to 14 digits allowed including +977",
                        ),
                        regex="^\\+?[0-9]{10,14}$",
                    )
                ],
            ),
        ),
    ]
