# Generated by Django 5.1.1 on 2025-01-12 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0010_event_requires_registration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="events",
            field=models.ForeignKey(
                error_messages="Event is required",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="event.event",
            ),
        ),
    ]
