name: Build and Push Nightly Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set lower case repository name
        run: |
          echo "REPOSITORY_LC=${REPOSITORY,,}" >> ${GITHUB_ENV}
        env:
          REPOSITORY: '${{ github.repository }}'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build, Tag, and Push Backend Image (Multi-Platform)
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --target production \
            -t ghcr.io/$REPOSITORY_LC/gnome-nepal-backend:nightly \
            --push .
