name: Build and Push Nightly docker image

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set lower case repository name
        run: |
          echo "REPOSITORY_LC=${REPOSITORY,,}" >> ${GITHUB_ENV}
        env:
          REPOSITORY: '${{ github.repository }}'

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 3: Sync Backend Image
      - name: Build, Tag, and Push Backend Image
        run: |
          docker compose build app
          docker tag gnome_backend:nightly ghcr.io/$REPOSITORY_LC/gnome-nepal-backend:$IMAGE_TAG
          docker push ghcr.io/$REPOSITORY_LC/gnome-nepal-backend:$IMAGE_TAG
          docker push ghcr.io/$REPOSITORY_LC/gnome-nepal-backend:$IMAGE_TAG
        env:
          IMAGE_TAG: '${{ secrets.IMAGE_TAG }}'


      # Step 4: Sync Worker Image
      - name: Build, Tag, and Push Worker Image
        run: |
          docker compose build worker_beat
          docker tag gnome-worker-beat:nightly ghcr.io/$REPOSITORY_LC/gnome-nepal-worker-beat:$IMAGE_TAG
          docker push ghcr.io/$REPOSITORY_LC/gnome-nepal-worker-beat:$IMAGE_TAG
          docker push ghcr.io/$REPOSITORY_LC/gnome-nepal-worker-beat:$IMAGE_TAG
        env:
          IMAGE_TAG: '${{ secrets.IMAGE_TAG }}'
