name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set lower case repository name
        run: |
          echo "REPOSITORY_LC=${REPOSITORY,,}" >> ${GITHUB_ENV}
        env:
          REPOSITORY: '${{ github.repository }}'

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: |
          docker build . -t ghcr.io/$REPOSITORY_LC/gnome-nepal-backend:latest

      - name: Push the Docker image
        run: |
          docker push ghcr.io/$REPOSITORY_LC/gnome-nepal-backend:latest
