name: GNOME server CI workflow

on:
  pull_request:

# sets up python code for linting issue
# and runnable issues
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      python-path: ${{ steps.python-setup.outputs.python-path }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      id: python-setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Add dummy .env file
      run: |
        cp env.example .env

  linting:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Use checkout and Python from setup job
      run: echo "Using previously checked out code and Python environment"

    - name: Install dev depenecies
      run: |
        python -m pip install black flake8

    - name: Run flake8 linting
      run: flake8 .

    - name: Run black for formatting check
      run: black . --check

  deployment_checking:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Use checkout and Python from setup job
      run: echo "Using previously checked out code and Python environment"
    
    - name: Find Python files
      id: find-files
      run: |
        found_files=$(find . -type f -name "*.py")
        echo "found_files=$found_files" >> $GITHUB_OUTPUT

    - name: Run Django system checks
      working-directory: repo  # Specify the correct working directory
      run: |
        python manage.py check || exit 1
