name: GNOME server CI workflow

on:
  pull_request:

# sets up python code for linting issue
# and runnable issues
jobs:
  lint_and_deploy_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        id: python-setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Make required directories
        run: |
          mkdir logs staticfiles
          touch logs/django_error.log

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Add dummy .env file
        run: |
          cp env.example .env

      - name: Run Django system checks
        run: |
          python manage.py check || exit 1
